# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boke', '0002_auto_20171106_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=512, verbose_name='描述'),
        ),
    ]
